"""The analysis module against the committed cache: every headline claim in the
paper must hold in the released data, the gap decomposition must be internally
consistent, and every macro referenced by paper/main.tex must be generated.
Needs only numpy."""
import json
import re
import unittest
from pathlib import Path

from qedrf import settings as S
from qedrf.analysis import (claims_check, escalation_decomposition,
                            findings_markdown, outage, variance_decomposition)

REPO = Path(__file__).resolve().parents[1]
RUNS = {k: Path(S.LOCAL_ART) / f"runs_{k}.json" for k in S.SCENARIOS}


def _load():
    return {k: json.loads(p.read_text(encoding="utf-8")) for k, p in RUNS.items()}


@unittest.skipUnless(all(p.exists() for p in RUNS.values()),
                     "cached runs (artifacts/runs_*.json) not present")
class AnalysisTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.raws = _load()

    def test_every_headline_claim_holds_in_cache(self):
        failing = [c for c in claims_check(self.raws) if not c["holds"]]
        self.assertEqual(failing, [],
                         "paper claims not supported by released cache: "
                         + "; ".join(c["claim"] for c in failing))

    def test_gap_decomposition_is_consistent(self):
        # escalation_drop + aggregation_drop must equal claimed - audited
        for raw in self.raws.values():
            e = escalation_decomposition(raw)
            self.assertAlmostEqual(e["escalation_drop"] + e["aggregation_drop"],
                                   e["claimed_mean"] - e["audited_mean"], places=9)
            self.assertGreaterEqual(e["escalation_drop"], 0)
            self.assertGreaterEqual(e["aggregation_drop"], 0)

    def test_outage_defended_below_undefended(self):
        for raw in self.raws.values():
            o_d = outage(raw, "defended")
            o_u = outage(raw, "undefended")
            for t in o_d["frac_below"]:
                self.assertLess(o_d["frac_below"][t], o_u["frac_below"][t])
                self.assertTrue(0.0 <= o_d["frac_below"][t] <= 1.0)

    def test_variance_decomposition_bounded_by_total(self):
        for raw in self.raws.values():
            v = variance_decomposition(raw)
            self.assertLessEqual(v["audit_seed_std"], v["total_std"] + 1e-9)
            self.assertLessEqual(v["model_seed_std"], v["total_std"] + 1e-9)

    def test_findings_report_renders_ascii(self):
        report = findings_markdown(self.raws)
        self.assertIn("Claims check", report)
        report.encode("ascii")  # must be printable on any console


@unittest.skipUnless(all(p.exists() for p in RUNS.values())
                     and (REPO / "paper" / "main.tex").exists(),
                     "cache or paper source not present")
class MacroCoverageTest(unittest.TestCase):
    def test_every_macro_used_in_paper_is_generated(self):
        """No inline number in the paper may reference a macro the benchmark
        does not generate — the repo's 'nothing hand-typed' guarantee."""
        macros_tex = (REPO / "paper" / "results_macros.tex").read_text(encoding="utf-8")
        defined = set(re.findall(r"\\newcommand\{\\(\w+)\}", macros_tex))
        main = (REPO / "paper" / "main.tex").read_text(encoding="utf-8")
        # candidate macro uses: our generated names all start with a known prefix
        prefixes = ("Asu", "Mmw", "Nmodel", "Naudit", "Nruns", "PassesPerUser",
                    "TotalWallMin")
        used = {m for m in re.findall(r"\\([A-Z]\w+)", main)
                if m.startswith(prefixes)}
        missing = used - defined
        self.assertEqual(missing, set(),
                         f"main.tex uses macros not generated by write_macros: {missing}")


if __name__ == "__main__":
    unittest.main()
